baseURL = 'https://keepintracks.com/'
languageCode = 'en'
title = "Keepin' Tracks"
theme = 'keepintracks-theme'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
    contentDir = 'content'
    dateFormat = 'January 2, 2006'
    
  [languages.fr]
    languageName = 'Fran√ßais'
    weight = 2
    contentDir = 'content'
    dateFormat = '2 January 2006'
